(() => {
  const cfg=window.SVETLONOSI_CONFIG,db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
  const $=id=>document.getElementById(id); const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
  let poll=null,opts=[],timer=null,lastClosedId=sessionStorage.getItem('svetlonosi_overlay_last_closed')||'';
  function startTimer(){clearInterval(timer);if(!poll?.ends_at){$('overlayTimer').textContent='';return;}const tick=()=>{const s=Math.max(0,Math.ceil((new Date(poll.ends_at)-Date.now())/1000));$('overlayTimer').textContent=s?`${s} s`:'';};tick();timer=setInterval(tick,1000);}
  async function refresh(){if(!poll)return;const {data}=await db.rpc('get_poll_results',{p_poll_id:poll.id});const map=new Map((data??[]).map(x=>[x.option_id,Number(x.votes)]));opts=opts.map(o=>({...o,votes:map.get(o.id)??0}));}
  function render(){if(!poll||!poll.overlay_visible){$('overlayCard').classList.add('stream-overlay-hidden');return;}$('overlayTitle').textContent='HLAS SBORU SVĚTLONOŠŮ';$('overlayQuestion').textContent=poll.question;$('overlayWinner').textContent='';$('overlaySub').textContent='';const total=opts.reduce((s,o)=>s+(o.votes??0),0);$('overlayResults').innerHTML=opts.map(o=>{const pct=total?Math.round(o.votes/total*100):0;return `<div class="stream-overlay-result"><strong><span>${esc(o.label)}</span><span>${poll.show_results?pct+'%':''}</span></strong>${poll.show_results?`<div class="stream-overlay-bar"><div style="width:${pct}%"></div></div>`:''}</div>`;}).join('');$('overlayCard').classList.remove('stream-overlay-hidden');startTimer();}
  async function loadOpen(){const {data}=await db.from('polls').select('*').eq('status','open').order('created_at',{ascending:false}).limit(1).maybeSingle();poll=data;if(!poll){$('overlayCard').classList.add('stream-overlay-hidden');return;}const r=await db.from('poll_options').select('*').eq('poll_id',poll.id).order('sort_order');opts=r.data??[];await refresh();render();}
  async function showLatestClosed(){const {data}=await db.from('polls').select('*').eq('status','closed').order('closed_at',{ascending:false}).limit(1).maybeSingle();if(!data||data.id===lastClosedId||!data.overlay_result_until)return;if(new Date(data.overlay_result_until)<=new Date())return;lastClosedId=data.id;sessionStorage.setItem('svetlonosi_overlay_last_closed',data.id);poll=null;clearInterval(timer);$('overlayTitle').textContent='ROZHODNUTÍ SBORU';$('overlayQuestion').textContent=data.question;$('overlayResults').innerHTML='';$('overlayTimer').textContent='';$('overlayWinner').textContent=data.winner_label||'Bez výsledku';$('overlaySub').textContent=data.total_votes!=null?`${data.total_votes} hlasů`:'';$('overlayCard').classList.remove('stream-overlay-hidden');setTimeout(()=>$('overlayCard').classList.add('stream-overlay-hidden'),Math.max(1000,new Date(data.overlay_result_until)-Date.now()));}
  db.channel('overlay-web').on('postgres_changes',{event:'*',schema:'public',table:'polls'},async p=>{if(p.new?.status==='closed')await showLatestClosed();else await loadOpen();}).on('postgres_changes',{event:'*',schema:'public',table:'votes'},async()=>{await refresh();render();}).subscribe();
  loadOpen();showLatestClosed();
})();
